---

- name: settings | Deploy nexus.properties
  template:
    src=nexus.properties.j2
    dest="{{ nexus_dir_base }}/{{ tar_dir_name.stdout }}/conf/nexus.properties"
    owner="{{ nexus_user }}"
    group="{{ nexus_user }}"
    mode=0644
  register: nexus_properties
  notify: restart nexus

- name: settings | Deploy index.html
  template:
     src=index.html.j2
     dest="{{ nexus_dir_sonatype_work }}/index.html"
     owner="{{ nexus_user }}"
     group="{{ nexus_group }}"
     mode=0644

- name: setting | Check for .git in sonatype_work/nexus/conf/.git
  stat:
    path="{{ nexus_dir_sonatype_work }}/nexus/conf/.git"
  register: sonatype_work_git
  when: nexus_config_pull

- name: setting | if no .get remove sonatype_work/nexus/conf
  file:
    path="{{ nexus_dir_sonatype_work }}/nexus/conf"
    state=absent
  when: nexus_config_pull and not sonatype_work_git.stat.exists

- name: settings | Fetch configuration from git
  git:
    repo="{{ nexus_config_repo }}"
    dest="{{ nexus_dir_sonatype_work }}/nexus/conf/"
    version="{{ nexus_config_version | default(omit) }}"
    force=yes
    accept_hostkey=yes
  sudo_user: "{{ nexus_user }}"
  when: nexus_config_pull