---
- name: Configure a test server
  hosts: all
  sudo: True
  roles:
        - { role: ansible-java8-oracle }
  tasks:
        - name: set java 8 default
          shell: update-java-alternatives -s java-8-oracle

        - name: install basic packages
          apt: pkg={{item}} state=installed
          with_items:
          - apache2
          - maven
          - git
          - unzip
          - rpm
           
        - name: change owner apache2
          sudo_user: vagrant
          command: bash -lc "sudo chown vagrant:vagrant /var/www/html"
 
        - name: add jenkins user
          user: name=jenkins

        - name: copy init.d script for the backend application
          copy: src=../cicd-lab-backend.sh dest=/etc/init.d/cicd-lab-backend mode=0755

        - name: set environment variables
          copy: src=../environment_run dest=/etc/environment

        - name: read public keys
          shell: cat /vagrant/jenkins_keys/id_rsa.pub
          register: publickey

        - name: set authorized keys
          authorized_key: user=jenkins key="{{publickey.stdout}}" manage_dir=yes
